### ISSUE TITLE
affixes/adjectives.lexc missing

### ISSUE THREAD

**Issue by TinoDidriksen** [giellalt/lang-rup#1]
`No rule to make target 'affixes/adjectives.lexc', needed by 'lexicon.tmp.lexc'.`

**Comment by Trondtr** [comment]
Why do we need affixes/adjectives.lexc? No makefile calls for it, and the fst compiles just fine.

**Comment by TinoDidriksen** [comment]
Looks like it builds now. It did not at the time of reporting this issue. Closing.
