### ISSUE TITLE
Recreate full history, fix start of available history

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-rup#2]
`rup` was once (April 1, 2015) moved from `langs/rup/` to `startup-langs/rup/` in the Subversion past of our repos. Two things did not go well when moving to git:

1) All history before the move is lost
1) The initial seven commits are detached from the rest of the commits, see screen shot:

![Bilde 17 09 2020 klokken 08 56](https://user-images.githubusercontent.com/1255285/93425917-aa700280-f8c3-11ea-9098-03d8c907b010.jpg)

Both issues should be fixed. One possible tip for how to fix it (and other similar cases) could be this stackoverflow suggestion:

https://stackoverflow.com/questions/25928921/how-can-i-splice-two-or-more-completely-unrelated-linear-branch-ancestries-i

Since no serious work has been done on this language in years, rewriting history and thus possibly/likely creating new sha's should have no serious side effects.

**Comment by snomos** [comment]
For reference: rup was created on March 29, 2014, in svn commit 91370. The last commit before the move was svn revision 110209, March 30, 2015. The svn revision of the move commit (which is in the git history) is 110296.

**Comment by Trondtr** [comment]
It seems this should be closed.

**Comment by snomos** [comment]
> It seems this should be closed.

Why is that? Nothing has been done yet.
